version: '3.7'

services:

 #postgres config
 postgres:
  image: postgres
  restart: always
  container_name: book_postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  volumes:
   - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql



  #backend Config
 src:
   image: booking
   container_name: book
   environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - spring.datasource.platform=postgres
    - spring.datasource.initialization-mode=always
   ports:
   - 8080:8081
   depends_on:
    - postgres


